baseURL: 'https://zhengzhou1992.github.io/'
languageCode: zh-cn
title: Joe's blog
theme: smol
keyword: "Docker, Kubernetes, Go, Golang, Python, DevOps, PaaS"
about_me: true
copyright: "Joe Zheng"
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
