baseURL: 'https://zhengzhou1992.github.io/'
languageCode: zh-cn
title: Joe's blog
dateFmt: "2006.01.27 15:04"
defaultcontentlanguage: zh
enableemoji: true
enablegitinfo: true
theme: smol
keyword: "Docker, Kubernetes, Go, Golang, Python, DevOps, PaaS"
about_me: true
copyright: "Joe Zheng"
permalinks:
  posts: /:year/:month/:title/
params:
  AuthorName: Joe Zheng
  GitHubUser: zhengzhou1992
  subtitle: 小川的代码和生活
  SidebarRecentLimit: 10
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: aboutme
      name: About
      url: /about
      weight: 4